# Author: Murtadha Marzouq
# Docker image: https://hub.docker.com/r/mmarzouq/snake-dev-ops
# Site: https://snakeops.azurewebsites.net/


# TODO: 
# - Add a "Deploy to Azure Web App" job
# - Create a Dockerfile for the app
# - Add the .dockerignore and .gitignore file to the app
# - Authenticate to Docker Hub and Azure by adding secrets to the repo




name: Build and deploy Node.js app to Azure Web App - SnakeOps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:

        ### ----- DOCKER IMAGE PATH ----- ###
          images: mmarzouq/snake-dev-ops
      - name: Log in to Docker Hub

      ### ----- LOGIN TO DOCKER  ----- ###

      #++++++++  DOCKER: https://hub.docker.com/settings/security?generateToken=true +++++++#


      #********  URL: https://github.com/MurtadhaM/{REPO}/settings/secrets/actions #********
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      ### ----- UPLOAD THE DOCKER IMAGE  ----- ###
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: 'latest'
          labels: ${{ steps.meta.outputs.labels }}






### ----- DEPLOYING THE APPLICATION TO AZURE  ----- ###          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SnakeOps'
          slot-name: 'Production'
### ----- AUTHENTICATION TOKEN FROM AZURE  ----- ###          
#******* URL: App Service ==> Deployment Center ==> Settings==>  Link *******#
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_98C9D1BDE9CA426499C8DB98D9E7B0B3 }}
          package: .
